const express = require('express');
const router = express.Router();
const { charPool, authPool } = require('../db');
const { requireGMLevel } = require('../middleware/auth');
const { audit } = require('../audit');
const path = require('path');
const fs = require('fs').promises;

// ── Write helpers ─────────────────────────────────────────────────────────────

// Tables where the character GUID column is named `guid`
const GUID_TABLES = [
  'characters',
  'character_account_data',
  'character_achievement',
  'character_achievement_progress',
  'character_action',
  'character_aura',
  'character_declinedname',
  'character_equipmentsets',
  'character_glyphs',
  'character_homebind',
  'character_inventory',
  'character_queststatus',
  'character_queststatus_daily',
  'character_queststatus_weekly',
  'character_queststatus_monthly',
  'character_queststatus_seasonal',
  'character_queststatus_rewarded',
  'character_reputation',
  'character_skills',
  'character_spell',
  'character_spell_cooldown',
  'character_talent',
];

// Escape a single value for use in a SQL INSERT statement
function escapeValue(val) {
  if (val === null || val === undefined) return 'NULL';
  if (Buffer.isBuffer(val)) return `0x${val.toString('hex')}`;
  if (typeof val === 'boolean') return val ? '1' : '0';
  if (typeof val === 'number' || typeof val === 'bigint') return String(val);
  if (val instanceof Date) {
    const p = n => String(n).padStart(2, '0');
    return `'${val.getFullYear()}-${p(val.getMonth()+1)}-${p(val.getDate())} ${p(val.getHours())}:${p(val.getMinutes())}:${p(val.getSeconds())}'`;
  }
  const s = String(val)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\0/g, '\\0');
  return `'${s}'`;
}

// Format a row as a SQL INSERT statement
function formatInsert(tableName, row) {
  const cols = Object.keys(row).map(c => `\`${c}\``).join(', ');
  const vals = Object.values(row).map(escapeValue).join(', ');
  return `INSERT INTO \`${tableName}\` (${cols}) VALUES (${vals});`;
}

// Check whether a table exists in the characters DB
async function tableExists(tableName) {
  const [rows] = await charPool.query(
    'SELECT COUNT(*) AS cnt FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = ?',
    [tableName]
  );
  return rows[0].cnt > 0;
}

async function generateDump(guid) {
  const lines = [];

  lines.push("-- IMPORTANT NOTE: THIS DUMPFILE IS MADE FOR USE WITH THE 'PDUMP' COMMAND ONLY - EITHER THROUGH INGAME CHAT OR ON CONSOLE!");
  lines.push("-- IMPORTANT NOTE: DO NOT apply it directly - it will irreversibly DAMAGE and CORRUPT your database! You have been warned!");
  lines.push(`-- Generated by AzerothCore Dashboard on ${new Date().toISOString()}`);
  lines.push('');

  // --- Simple GUID tables ---
  for (const table of GUID_TABLES) {
    if (!await tableExists(table)) continue;
    const [rows] = await charPool.query(`SELECT * FROM \`${table}\` WHERE guid = ?`, [guid]);
    for (const row of rows) lines.push(formatInsert(table, row));
  }

  // --- Pets (owner = guid) ---
  const [pets] = await charPool.query('SELECT * FROM `character_pet` WHERE owner = ?', [guid]);
  const petIds = pets.map(p => p.id);
  for (const pet of pets) lines.push(formatInsert('character_pet', pet));

  if (petIds.length > 0) {
    const petTables = [
      { name: 'character_pet_declinedname', col: 'id' },
      { name: 'pet_aura',           col: 'guid' },
      { name: 'pet_spell',          col: 'guid' },
      { name: 'pet_spell_cooldown', col: 'guid' },
    ];
    for (const { name, col } of petTables) {
      if (!await tableExists(name)) continue;
      const [rows] = await charPool.query(`SELECT * FROM \`${name}\` WHERE \`${col}\` IN (?)`, [petIds]);
      for (const row of rows) lines.push(formatInsert(name, row));
    }
  }

  // --- Mail (receiver = guid) ---
  const [mails] = await charPool.query('SELECT * FROM `mail` WHERE receiver = ?', [guid]);
  const mailIds = mails.map(m => m.id);
  for (const mail of mails) lines.push(formatInsert('mail', mail));

  let mailItemGuids = [];
  if (mailIds.length > 0) {
    const [mailItems] = await charPool.query('SELECT * FROM `mail_items` WHERE mail_id IN (?)', [mailIds]);
    mailItemGuids = mailItems.map(mi => mi.item_guid);
    for (const row of mailItems) lines.push(formatInsert('mail_items', row));
  }

  // --- Item instances (inventory + mail items) ---
  const [invRows] = await charPool.query('SELECT item FROM `character_inventory` WHERE guid = ?', [guid]);
  const inventoryItemGuids = invRows.map(r => r.item).filter(Boolean);

  const allItemGuids = [...new Set([...inventoryItemGuids, ...mailItemGuids])];
  if (allItemGuids.length > 0) {
    const [items] = await charPool.query('SELECT * FROM `item_instance` WHERE guid IN (?)', [allItemGuids]);
    for (const row of items) lines.push(formatInsert('item_instance', row));

    if (await tableExists('character_gifts')) {
      const [gifts] = await charPool.query('SELECT * FROM `character_gifts` WHERE item_guid IN (?)', [allItemGuids]);
      for (const row of gifts) lines.push(formatInsert('character_gifts', row));
    }
  }

  return lines.join('\n');
}

// ── Load helpers ──────────────────────────────────────────────────────────────

// GUID type tags (mirror AzerothCore GuidType enum)
const GT = {
  CHAR:      'CHAR',
  ACCOUNT:   'ACCOUNT',
  ITEM:      'ITEM',
  MAIL:      'MAIL',
  PET:       'PET',
  EQUIP_SET: 'EQUIP_SET',
  NULL:      'NULL',
};

// Columns that allow zero / NULL (empty equipment / bag slots)
const ALLOW_ZERO_COLS = new Set([
  'bag',
  ...Array.from({ length: 19 }, (_, i) => `item${i}`),
]);

// Per-table column → GUID type mapping (from PlayerDump.cpp InitializeTables)
const DTT_CHAR_TABLES = [
  'character_account_data', 'character_achievement', 'character_achievement_progress',
  'character_action', 'character_aura', 'character_declinedname', 'character_glyphs',
  'character_homebind', 'character_queststatus', 'character_queststatus_daily',
  'character_queststatus_weekly', 'character_queststatus_monthly',
  'character_queststatus_seasonal', 'character_queststatus_rewarded',
  'character_reputation', 'character_skills', 'character_spell',
  'character_spell_cooldown', 'character_talent',
];

const TABLE_GUID_COLS = {
  characters: {
    guid: GT.CHAR, account: GT.ACCOUNT,
    deleteInfos_Account: GT.NULL, deleteInfos_Name: GT.NULL, deleteDate: GT.NULL,
  },
  character_equipmentsets: {
    guid: GT.CHAR, setguid: GT.EQUIP_SET,
    ...Object.fromEntries(Array.from({ length: 19 }, (_, i) => [`item${i}`, GT.ITEM])),
  },
  character_inventory:       { guid: GT.CHAR, bag: GT.ITEM, item: GT.ITEM },
  character_pet:             { id: GT.PET,    owner: GT.CHAR },
  character_pet_declinedname:{ id: GT.PET,    owner: GT.CHAR },
  mail:                      { id: GT.MAIL,   receiver: GT.CHAR },
  mail_items:                { mail_id: GT.MAIL, item_guid: GT.ITEM, receiver: GT.CHAR },
  item_instance:             { guid: GT.ITEM, owner_guid: GT.CHAR },
  character_gifts:           { guid: GT.CHAR, item_guid: GT.ITEM },
  pet_aura:                  { guid: GT.PET },
  pet_spell:                 { guid: GT.PET },
  pet_spell_cooldown:        { guid: GT.PET },
};
for (const t of DTT_CHAR_TABLES) TABLE_GUID_COLS[t] = { guid: GT.CHAR };

// Parse the VALUES list from the inner string of a SQL INSERT
function parseValueList(str) {
  const values = [];
  let i = 0;

  while (i < str.length) {
    // skip leading whitespace and commas
    while (i < str.length && (str[i] === ' ' || str[i] === '\t' || str[i] === ',')) i++;
    if (i >= str.length) break;

    if (str[i] === "'") {
      // Quoted string literal
      let val = "'";
      i++;
      while (i < str.length) {
        if (str[i] === '\\' && i + 1 < str.length) {
          val += str[i] + str[i + 1];
          i += 2;
        } else if (str[i] === "'") {
          val += "'";
          i++;
          break;
        } else {
          val += str[i++];
        }
      }
      // AC-native dumps write 'NULL' as a quoted string; normalize to unquoted NULL
      values.push(val === "'NULL'" ? 'NULL' : val);
    } else {
      // Unquoted: NULL, integer, float, 0x...
      let val = '';
      while (i < str.length && str[i] !== ',') val += str[i++];
      const trimmed = val.trim();
      if (trimmed) values.push(trimmed);
    }
  }

  return values;
}

// Parse a full INSERT statement → { tableName, cols, values } or null
function parseInsert(line) {
  const tableMatch = line.match(/^INSERT INTO `([^`]+)`/i);
  if (!tableMatch) return null;
  const tableName = tableMatch[1];

  // Find columns section (first balanced parentheses)
  const colsOpen = line.indexOf('(');
  if (colsOpen === -1) return null;
  const colsClose = line.indexOf(')', colsOpen);
  if (colsClose === -1) return null;
  const cols = line.slice(colsOpen + 1, colsClose)
    .split(',')
    .map(c => c.trim().replace(/`/g, ''));

  // Find VALUES keyword, then the opening paren of the values list
  const valuesIdx = line.indexOf('VALUES', colsClose);
  if (valuesIdx === -1) return null;
  const valsOpen = line.indexOf('(', valuesIdx);
  if (valsOpen === -1) return null;

  // Walk forward to find the matching closing paren, respecting string literals
  let valsClose = -1;
  let inStr = false;
  for (let i = valsOpen + 1; i < line.length; i++) {
    if (inStr) {
      if (line[i] === '\\') { i++; continue; }
      if (line[i] === "'") inStr = false;
    } else {
      if (line[i] === "'") { inStr = true; continue; }
      if (line[i] === ')') { valsClose = i; break; }
    }
  }
  if (valsClose === -1) return null;

  const values = parseValueList(line.slice(valsOpen + 1, valsClose));
  if (cols.length !== values.length) return null;

  return { tableName, cols, values };
}

// Unescape a SQL quoted string value → plain JS string (or null for SQL NULL)
function unquoteString(val) {
  if (!val || val === 'NULL') return null;
  if (!val.startsWith("'")) return val;
  return val.slice(1, -1)
    .replace(/\\'/g, "'").replace(/\\\\/g, '\\')
    .replace(/\\n/g, '\n').replace(/\\r/g, '\r').replace(/\\0/g, '\0');
}

// Escape a plain JS string → SQL quoted string
function quoteString(s) {
  return `'${String(s)
    .replace(/\\/g, '\\\\').replace(/'/g, "\\'")
    .replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\0/g, '\\0')}'`;
}

// Remap a single value according to its GUID type
function remapValue(val, colName, guidType, { newCharGuid, accountId, itemMap, mailMap, petMap, equipMap, offsets }) {
  switch (guidType) {
    case GT.CHAR:    return String(newCharGuid);
    case GT.ACCOUNT: return String(accountId);
    case GT.NULL:    return 'NULL';

    case GT.ITEM: {
      const allowZero = ALLOW_ZERO_COLS.has(colName);
      if (allowZero && (val === 'NULL' || val === '0')) return val;
      const n = parseInt(val);
      if (isNaN(n) || n === 0) return val;
      if (!itemMap.has(n)) itemMap.set(n, offsets.item + itemMap.size);
      return String(itemMap.get(n));
    }
    case GT.MAIL: {
      const n = parseInt(val);
      if (isNaN(n)) return val;
      if (!mailMap.has(n)) mailMap.set(n, offsets.mail + mailMap.size);
      return String(mailMap.get(n));
    }
    case GT.PET: {
      const n = parseInt(val);
      if (isNaN(n)) return val;
      if (!petMap.has(n)) petMap.set(n, offsets.pet + petMap.size);
      return String(petMap.get(n));
    }
    case GT.EQUIP_SET: {
      const n = parseInt(val);
      if (isNaN(n)) return val;
      if (!equipMap.has(n)) equipMap.set(n, offsets.equipSet + equipMap.size);
      return String(equipMap.get(n));
    }
    default:
      return val;
  }
}

// Query the next-available GUID offsets from the live DB
async function getGuidOffsets() {
  const [[cr]] = await charPool.query('SELECT COALESCE(MAX(guid),0)+1 AS v FROM characters');
  const [[ir]] = await charPool.query('SELECT COALESCE(MAX(guid),0)+1 AS v FROM item_instance');
  const [[mr]] = await charPool.query('SELECT COALESCE(MAX(id),0)+1   AS v FROM mail');
  const [[pr]] = await charPool.query('SELECT COALESCE(MAX(id),0)+1   AS v FROM character_pet');
  const [[er]] = await charPool.query('SELECT COALESCE(MAX(setguid),0)+1 AS v FROM character_equipmentsets');
  return {
    char:     Number(cr.v),
    item:     Number(ir.v),
    mail:     Number(mr.v),
    pet:      Number(pr.v),
    equipSet: Number(er.v),
  };
}

// Load a dump into the characters DB
async function loadDump(dumpContent, { accountId, characterName = '', characterGuid = 0 }) {
  // Validate account exists
  const [[acct]] = await authPool.query('SELECT id FROM account WHERE id = ?', [accountId]);
  if (!acct) throw new Error('Account not found');

  // Check character count for this account (max 10)
  const [[{ cnt }]] = await charPool.query(
    'SELECT COUNT(*) AS cnt FROM characters WHERE account = ?', [accountId]
  );
  if (cnt >= 10) throw new Error('Account already has the maximum of 10 characters');

  // Get GUID offsets
  const offsets = await getGuidOffsets();

  // Determine new character GUID
  let newCharGuid = (characterGuid > 0) ? characterGuid : offsets.char;
  const [[existingChar]] = await charPool.query('SELECT guid FROM characters WHERE guid = ?', [newCharGuid]);
  if (existingChar) newCharGuid = offsets.char;

  // Validate / clear the requested name
  let finalName = characterName.trim();
  let forceRename = false;
  if (finalName) {
    const [[nameExists]] = await charPool.query('SELECT guid FROM characters WHERE name = ?', [finalName]);
    if (nameExists) { finalName = ''; forceRename = true; }
  }

  // GUID maps (old → new)
  const itemMap  = new Map();
  const mailMap  = new Map();
  const petMap   = new Map();
  const equipMap = new Map();

  const ctx = { newCharGuid, accountId, itemMap, mailMap, petMap, equipMap, offsets };

  const statements = [];
  let dumpOriginalName = '';

  for (const rawLine of dumpContent.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('--') || line.includes('IMPORTANT NOTE:')) continue;

    const parsed = parseInsert(line);
    if (!parsed) continue;

    const { tableName, cols, values } = parsed;
    const guidCols = TABLE_GUID_COLS[tableName];
    if (!guidCols) continue; // unknown / unsupported table — skip safely

    // Remap each column value
    const newValues = values.map((val, idx) => {
      const colLower = cols[idx].toLowerCase();
      // Case-insensitive column lookup
      const colKey = Object.keys(guidCols).find(k => k.toLowerCase() === colLower);
      if (!colKey) return val;
      return remapValue(val, colKey, guidCols[colKey], ctx);
    });

    // DTT_CHARACTER extra handling: name + at_login
    if (tableName === 'characters') {
      const nameIdx    = cols.findIndex(c => c.toLowerCase() === 'name');
      const atLoginIdx = cols.findIndex(c => c.toLowerCase() === 'at_login');

      if (nameIdx !== -1) dumpOriginalName = unquoteString(newValues[nameIdx]) || '';

      if (finalName) {
        if (nameIdx !== -1) newValues[nameIdx] = quoteString(finalName);
      } else {
        // Generate temporary name: truncated original + GUID in hex (like AC does)
        const guidHex    = newCharGuid.toString(16).toUpperCase();
        const maxNameLen = 12;
        const origSlice  = dumpOriginalName.slice(0, maxNameLen - guidHex.length);
        const tempName   = origSlice + guidHex;
        if (nameIdx    !== -1) newValues[nameIdx]    = quoteString(tempName);
        if (atLoginIdx !== -1) newValues[atLoginIdx] = '1'; // rename on next login
        finalName = tempName;
        forceRename = true;
      }
    }

    // Reconstruct the INSERT statement
    const colList = cols.map(c => `\`${c}\``).join(', ');
    statements.push(`INSERT INTO \`${tableName}\` (${colList}) VALUES (${newValues.join(', ')});`);
  }

  if (statements.length === 0) throw new Error('No valid INSERT statements found in dump');

  // Execute everything in a single transaction
  const conn = await charPool.getConnection();
  try {
    await conn.beginTransaction();
    for (const stmt of statements) await conn.query(stmt);
    await conn.commit();
  } catch (err) {
    await conn.rollback();
    throw err;
  } finally {
    conn.release();
  }

  return {
    characterGuid: newCharGuid,
    characterName: finalName || dumpOriginalName,
    forceRename,
    tablesLoaded: statements.length,
  };
}

// ── Routes ────────────────────────────────────────────────────────────────────

// GET /api/pdump/default-path
// Returns the configured PDUMP_OUTPUT_PATH so the frontend can pre-fill the input
router.get('/default-path', requireGMLevel(2), (req, res) => {
  const dir = process.env.PDUMP_OUTPUT_PATH || '';
  res.json({ path: dir ? path.resolve(dir) : '' });
});

// GET /api/pdump/list-files
// Lists .sql/.txt dump files in the configured PDUMP_OUTPUT_PATH directory
router.get('/list-files', requireGMLevel(2), async (req, res) => {
  const dir = process.env.PDUMP_OUTPUT_PATH || '';
  if (!dir) return res.json({ files: [] });
  const resolved = path.resolve(dir);
  try {
    const entries = await fs.readdir(resolved, { withFileTypes: true });
    const files = entries
      .filter(e => e.isFile() && /\.(sql|txt)$/i.test(e.name))
      .map(e => ({ name: e.name, path: path.join(resolved, e.name) }));
    return res.json({ files });
  } catch {
    return res.json({ files: [] });
  }
});

// POST /api/pdump/load
// Body: { content?: string, filePath?: string, accountId: number, characterName?: string, characterGuid?: number }
//   content   → raw dump text sent from the browser
//   filePath  → path to a dump file on the server machine
//   accountId → target account to assign the character to
router.post('/load', requireGMLevel(2), async (req, res) => {
  const { content, filePath, accountId, characterName = '', characterGuid = 0 } = req.body || {};

  if (!accountId) return res.status(400).json({ error: 'accountId is required' });

  let dumpContent;
  try {
    if (filePath) {
      dumpContent = await fs.readFile(path.resolve(filePath), 'utf8');
    } else if (content) {
      dumpContent = content;
    } else {
      return res.status(400).json({ error: 'Provide either content or filePath' });
    }
  } catch (err) {
    return res.status(400).json({ error: `Cannot read dump file: ${err.message}` });
  }

  try {
    const result = await loadDump(dumpContent, {
      accountId: parseInt(accountId, 10),
      characterName,
      characterGuid: parseInt(characterGuid, 10) || 0,
    });
    audit(req, 'pdump.load', `character=${result.characterName} guid=${result.characterGuid} account=${accountId} source=${filePath ? `path:${path.resolve(filePath)}` : 'upload'}`);
    return res.json({ ok: true, ...result });
  } catch (err) {
    console.error('[pdump load] Error:', err);
    audit(req, 'pdump.load', `account=${accountId} error=${err.message}`, null, false);
    return res.status(500).json({ error: err.message });
  }
});

// POST /api/pdump/:guid  (write / export)
// Body: { filePath?: string }
//   filePath set  → save to server path, return JSON { ok, path, characterName }
//   filePath omit → return dump as downloadable text/plain attachment
router.post('/:guid', requireGMLevel(2), async (req, res) => {
  const guid = parseInt(req.params.guid, 10);
  if (!guid || guid <= 0) return res.status(400).json({ error: 'Invalid GUID' });

  const { filePath } = req.body || {};

  try {
    const [[char]] = await charPool.query('SELECT name FROM `characters` WHERE guid = ?', [guid]);
    if (!char) return res.status(404).json({ error: 'Character not found' });

    const dumpContent = await generateDump(guid);

    if (filePath) {
      const resolved = path.resolve(filePath);
      await fs.mkdir(path.dirname(resolved), { recursive: true });
      await fs.writeFile(resolved, dumpContent, 'utf8');
      audit(req, 'pdump.write', `character=${char.name} guid=${guid} path=${resolved}`);
      return res.json({ ok: true, path: resolved, characterName: char.name });
    }

    const fileName = `${char.name}_${guid}_${Date.now()}.sql`;
    audit(req, 'pdump.write', `character=${char.name} guid=${guid} output=download`);
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
    return res.send(dumpContent);

  } catch (err) {
    console.error('[pdump write] Error:', err);
    if (!res.headersSent) return res.status(500).json({ error: err.message });
  }
});

module.exports = router;
